- name: Provision an EC2 instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "ansible-webserver"
    id: "ansible-web-server"
    group_id: "{{ security_group.group_id }}"
    image: "{{ image }}"
    instance_type: t2.micro
    region: "{{ region }}"
    wait: true
    count: 1
  register: webserver

- name: Tag the webserver EC2 instance
  ec2_tag:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    resource: "{{ webserver.instances[0].id }}"
    state: present
    tags:
      Name: Webserver
