---
  # Search and download Windows updates
- name: Search and download Windows updates without installing them
  win_updates:
    state: searched

- name: Install all security, critical, and rollup updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
#      - UpdateRollups
    reboot: yes