# Install MongoDB for Grayloy
# Steps taken from official Graylog documentation at https://docs.graylog.org/en/3.2/pages/installation/os/ubuntu.html
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: Add source repository into sources list.
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse
    state: present
    filename: mongodb-org-4.0
    update_cache: yes    

- name: Install MongoDB
  vars:
    packages:
      - mongodb
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest
