# Install MongoDB for Grayloy
# Steps taken from official Graylog documentation at https://docs.graylog.org/en/3.2/pages/installation/os/ubuntu.html

- name: Add signing key
  apt_key:
    url: hkp://keyserver.ubuntu.com:80
    state: present

- name: Add source repository into sources list.
  apt_repository:
    repo: deb-src https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse
    state: present
    filename: mongodb-org-4.0.list

- name: install MongoDB
  vars:
    packages:
      - mongodb-org
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest

- name: Enable service
  service:
    name: mongod.service
    enabled: yes

- name: Start service
  service:
    name: mongod.service
    state: started