---
- name: Make sure universe repository is enabled
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
    update_cache: true

- name: Install dependencies icluding Java
  vars:
    packages:
      - apt-transport-https
      - openjdk-8-jre-headless
      - uuid-runtime
      - pwgen
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest