---
- name: Install dependencies including Java
  vars:
    packages:
      - apt-transport-https
      - openjdk-8-jre-headless
      - uuid-runtime
      - pwgen
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest